// Generated by CoffeeScript 1.3.3
(function() {

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Express'
    });
  };

  exports.blog = function(req, res) {
    return res.render('index', {
      title: 'Express'
    });
  };

  exports.about = function(req, res) {
    return res.render('index', {
      title: 'Exas'
    });
  };

}).call(this);
