// Generated by CoffeeScript 1.3.3
(function() {
  var request, should;

  request = require('request');

  should = require('should');

  describe('Sample test', function() {
    return it('should be true', function() {
      return true.should.equal(true);
    });
  });

}).call(this);
