// Generated by CoffeeScript 1.3.3
(function() {
  var app, cake, exec, express, fs, http, routes, server;

  express = require('express');

  fs = require('fs');

  exec = require('child_process').exec;

  routes = require('./routes/routes');

  http = require('http');

  app = express();

  cake = './node_modules/coffee-script/bin/cake';

  app.settings.env = 'development';

  app.configure(function() {
    app.set('port', process.env.PORT || 8888);
    app.set('views', './views');
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"]('./compiled/client'));
  });

  app.configure('development', function() {
    app.locals.pretty = true;
    app.use(express.logger('dev'));
    return app.use(express.errorHandler());
  });

  app.configure('production', function() {
    var logFile;
    exec(cake + ' ' + app.settings.env);
    logFile = fs.createWriteStream('./log.log', {
      flags: 'w'
    });
    return app.use(express.logger({
      stream: logFile
    }, 'dev'));
  });

  app.get('/', routes.index);

  app.get('/blog', routes.blog);

  app.get('/about', routes.about);

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log('Listening on port ' + app.get('port') + ', Env: ' + app.settings.env);
  });

}).call(this);
